singleQuote: true
semi: false
printWidth: 120
useTabs: false
arrowParens: avoid
tabWidth: 2
trailingComma: all
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
